#!/usr/bin/python
# coding: UTF-8

import fileinput
import re
import pandas as pd

#------------------------------------------
# Part 2:  fixing translation errors -> fixing syntax erros
# Translation errors

# fixes the "First codon is not a start codon error"
def first(location):
    rewrite = location.split('(')
    if (rewrite[0] == "complement"): # complement(....) and complement(join(....)) case , fix: (xxx..xxx,xxx..>xxx) (including complement/complemntjoin)
        adding_sign = location.rsplit("..",1) 
        location = adding_sign[0] + "..>" + adding_sign[1]

    else : # (if rewrite[0] != complement)
        if (rewrite[0] == "join"):  # join(....) case , fix: (<xxx..xxx,xxx..xxx) (including join)
            location = "join(<" + rewrite[1]
        else :
            location = "<" + location # (....) case , fix: (<xxx..xxx,xxx..xxx)
    return location

# fixes the "Final codon is not a stop codon error"
def final(location):
    rewrite = location.split('(')
    if (rewrite[0] == "complement"): 
        if (rewrite[1] == "join"): # complement(join(....)) case , fix: (<xxx..xxx,xxx..xxx) (including complementjoin)
            location = "complement(join(<" + rewrite[2]
        else : # complement(....) case , fix: (<xxx..xxx,xxx..xxx) (including complement)
            location = "complement(<" + rewrite[1]

    else : # (if rewrite[0] != complement) # join(....) and (....) case , fix: (xxx..xxx,xxx..>xxx) (including join or not)
        adding_sign = location.rsplit("..",1) 
        location = adding_sign[0] + "..>" + adding_sign[1]

    return location



args = sys.argv
transChecker_errors = args[0] # output of transChecker
mss_file = args[1] # converted mss file 
filename = "what_to_fix"    # generated file with information how to solve things


with fileinput.FileInput(filename) as out_file
    with fileinput.FileInput(transChecker_errors) as in_file
        for line in in_handle:
        if line[0] == '>': # new location of error
            location = line.split()[1]
            oldLocation = location
            while line[0:2] != "//": # until errors for this location dont end
                line = fileR.readline()
                if (line.split()[0] == "TC0017:ER2:"): # first codon error
                    location = first(location)
                if (line.split()[0] == "TC0018:ER2:"): # final codon error
                    location = final(location)
            uninterrupted = oldLocation + ";" + location + "\n" # write to fix file in "bad_location;location_fix" manner
            in_file2.write(uninterrupted)
        


with fileinput.FileInput(mss_file, inplace=True) as out_file:
    x = 0 # position in replacement file
    for line in out_file: # for line in mss file
            splitted = re.split(r'\t+', line) # splitted line by tabs
            flag = 0 # flag to check if replacement in the line is being made
            if splitted[1] == "CDS": # if given line is CDS of mRNA header
                with open(filename) as in_file: # with open file with things that need to be fixed
                    for linee in in_file.readlines()[x:]: # opening the file from a new position as to not overwrite the fixed errors
                        replacement = linee.split(";") # version giving an error and the new version are separated my a ';' in a file
                        r1 = replacement[0] # old version
                        r2 = replacement[1] # new version
                        if r1 == splitted[2]: # if location is approptiate
                            x += 1 # new file opening position
                            flag = 1 # replacement needs to be done                           
                            savedR1 = r1.rstrip('\n') # stripping the line of the newline     
                            savedR2 = r2.rstrip('\n')                                         
                            break;
            if flag == 1 : print(line.replace(savedR1,savedR2), end='') # replacement to be done ###
            else :  print(line, end = '') # no replacement



#---------------------------------------------------
# Syntax errors


with fileinput.FileInput(mss_file, inplace = True) as file:
    for line in file:
        line = re.sub(r"\(\w+\s\w+.+\)","",line) # remove species names
        line = re.sub(r"\\","",line) # remove backslashes
        match  = re.search(r"(Scaffold)([0-9]+)",line) 
        if match:
            replacement = "BOPP0" + str(int(match.group(2)) + 1000000) 
            line = re.sub(match.group(0),replacement,line) # replace "scaffold" with names appointed by the DDBJ
        match  = re.search(r"GBI",line) 
        if match:
            replacement = "GBIM" 
            line = re.sub(match.group(0),replacement,line) 

        print(line, end = '')

